#!/bin/bash

set -e

./scripts/build-sbt-reactjs

echo "Tools built"
echo "************************************************************"
echo "************************************************************"
echo "************************************************************"
pwd

./scripts/write-git-version
pwd
cat ./git-version.txt
sbt "npm install"
sbt clean compile
