#!/bin/bash

set -e

./scripts/build-sbt-reactjs

echo "Tools built"
echo "************************************************************"
echo "************************************************************"
echo "************************************************************"
pwd
sbt "npm install"
sbt clean compile
