#!/bin/bash

set -e


pwd
./scripts/write-git-version
pwd
cat ./git-version.txt


./scripts/build-sbt-reactjs

echo "Tools built"
echo "************************************************************"
echo "************************************************************"
echo "************************************************************"
sbt "npm install"
sbt clean compile
