#!/bin/bash

echo set -e

CWD=$(pwd)
APPNAME=${APPNAME:-link-mobile-observations}
ZIP=target/aws/link-mobile-observations.zip

cd ansible || exit
rm -rf roles/*
ansible-galaxy install -f -r requirements.yml
ansible-playbook ${APPNAME}-build.yml -e "appname=${APPNAME}"
cd $CWD

./scripts/write-version
./scripts/write-git-version
source ./version.txt
echo Version $TAG
source ./git-version.txt
echo Git tag
pwd
cat ./git-version.txt

echo "clean old link images '| xargs docker rmi'"
docker images -a | grep link

./scripts/build-sbt-reactjs

sbt "npm install" > /dev/null
sbt clean stage docker:publishLocal
echo "Docker local image created"

docker images

echo "Docker tagging new image"
echo docker tag $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/intersection/link-mobile-observations:$TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/intersection/link-mobile-observations:$GITTAG

AWS_ACCOUNT_ID=028957328603
docker tag $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/intersection/link-mobile-observations:$TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/intersection/link-mobile-observations:$GITTAG

echo "Docker local re tagged with git tag"

docker images

AWS_ACCOUNT_ID=028957328603
eval $(aws ecr get-login --registry-ids $AWS_ACCOUNT_ID --region us-east-1 --no-include-email)

echo docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/intersection/link-mobile-observations:$GITTAG

#Point Beanstalk configuration file to correct image
sed -i='' "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" config/Dockerrun.aws.json
sed -i='' "s/<TAG>/$GITTAG/" config/Dockerrun.aws.json

#Zip the dockerrun file and the ebextensions directory
mkdir -p target/aws
mv config/Dockerrun.aws.json . && mv config/ebextensions .ebextensions
echo "---------------- Docker run --------------"
cat Dockerrun.aws.json
echo "---------------- Docker run --------------"
zip -r $ZIP Dockerrun.aws.json .ebextensions config/link-mobile-observations-cloudformation.json