#!/bin/bash

echo set -e


./scripts/write-git-version

echo "clean old link images '| xargs docker rmi'"
docker rmi $(docker images -a | grep link | awk '{print $3}')


./scripts/build-sbt-reactjs

sbt "npm install" > /dev/null

source ./git-version.txt
echo Git Tag $GITTAG


sbt clean stage docker:publishLocal
echo "Docker local image created"

docker tag intersection/link-mobile-observations:1.0-SNAPSHOT intersection/link-mobile-observations:$GITTAG
echo " Docker tag  done"

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

docker push intersection/link-mobile-observations:$GITTAG

docker logout

#echo "package done"
#sed -i='' "s/<TAG>/$GITTAG/" ansible/swarm-upload.yml
#cat ansible/swarm-upload.yml
#aws s3 cp s3://dev-nyc-secrets/vault_pass .
#/usr/local/bin/ansible-playbook -vvv --vault-password-file=vault_pass -i ansible/inventories/dev ansible/swarm-upload.yml

